module.exports = {
  RESET_ALL_RECIPES: "RESET_ALL_RECIPES",
  RECIPE_ITEMS_RECEIVED: "RECIPE_ITEMS_RECEIVED",
  RECIPE_ITEM_CREATED: "RECIPE_ITEM_CREATED",
  RECIPE_ITEM_REMOVED: "RECIPE_ITEM_REMOVED",
  SINGLE_RECIPE_ITEM_CREATED: "SINGLE_RECIPE_ITEM_CREATED"
};
